browser= chrome
url= https://naveenautomationlabs.com/opencart/index.php?route=account/login

username= automation123@opencart.com
password= automation1234

headless= false
incognito= false

highlight= true